"""
Django settings for Forms project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from decouple import config

# Clave secreta de Django (para seguridad, cookies, sesiones, etc.)
SECRET_KEY = config("SECRET_KEY", "")

# DEBUG = True → modo desarrollo (muestra errores detallados)
# DEBUG = False → modo producción (no muestra errores)
DEBUG = config("DEBUG", cast=bool, default=False)

# Si no hay SECRET_KEY, el proyecto no debe arrancar
if SECRET_KEY == "":
    raise ValueError("SECRET_KEY no establecida")

# ALLOWED_HOSTS indica qué dominios pueden acceder al proyecto
if DEBUG:
    # En desarrollo permitimos cualquier dominio
    ALLOWED_HOSTS = ["*"]
else:
    # En producción solo se permiten dominios específicos
    ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=[])

    # Si viene como string desde .env, se convierte en lista
    if isinstance(ALLOWED_HOSTS, str):
        ALLOWED_HOSTS = ALLOWED_HOSTS.split(",")  # separados por comas
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



DEBUG = True



# Application definition

INSTALLED_APPS = [
    # con esto especificamos que se deben leer los headers de las peticiones
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Para que django sepa que amos a trabajar con servicios API REST
    'rest_framework',
    'rest_framework_simplejwt',
    'forms_management.apps.FormsManagementConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Forms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Forms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKEN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-es'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

ASSETS_DIR = BASE_DIR / 'assets'
STATIC_URL = '/static/'
STATICFILES_DIRS = [ASSETS_DIR, 'static']
STATIC_ROOT = ASSETS_DIR / 'collected_static'

MEDIA_URL = '/media/'
MEDIA_ROOT = ASSETS_DIR / 'media'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'forms_management.User'