# Generated by Django 6.0.3 on 2026-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioRespuestaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('formStep', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', help_text='(Cumpolsory)', max_length=3, verbose_name='Step')),
                ('form_interest', models.BooleanField(default=True)),
                ('form_reschedule', models.BooleanField(default=True)),
                ('form_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Form_response',
                'verbose_name_plural': 'Forms_responses',
                'db_table': 'forms',
            },
        ),
    ]
