# Generated by Django 6.0.3 on 2026-03-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0002_formulariorespuestamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariorespuestamodel',
            name='formStep',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', help_text='(Cumpolsory)', max_length=3, verbose_name='Step'),
        ),
    ]
