# Generated by Django 6.0.3 on 2026-03-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0003_alter_formulariorespuestamodel_formstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariorespuestamodel',
            name='form_interest',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulariorespuestamodel',
            name='form_reschedule',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
