# Generated by Django 6.0.3 on 2026-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0004_alter_formulariorespuestamodel_form_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariorespuestamodel',
            name='form_date',
        ),
        migrations.RemoveField(
            model_name='formulariorespuestamodel',
            name='form_interest',
        ),
        migrations.RemoveField(
            model_name='formulariorespuestamodel',
            name='form_reschedule',
        ),
        migrations.AddField(
            model_name='formulariorespuestamodel',
            name='dataJson',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulariorespuestamodel',
            name='formStep',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', help_text='(Cumpolsory)', max_length=3, null=True, verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='formulariorespuestamodel',
            name='lead_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
