# Generated by Django 6.0.3 on 2026-03-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0005_remove_formulariorespuestamodel_form_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariorespuestamodel',
            old_name='formStep',
            new_name='form_step',
        ),
    ]
