# Generated by Django 6.0.3 on 2026-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0006_rename_formstep_formulariorespuestamodel_form_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('taskId', models.CharField(max_length=50)),
                ('formStep', models.CharField(max_length=50)),
                ('formDate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
            },
        ),
    ]
