# Generated by Django 6.0.3 on 2026-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0007_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='urlTask',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='formDate',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='formStep',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=3),
        ),
    ]
