# Generated by Django 6.0.3 on 2026-03-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0008_taskmodel_urltask_alter_taskmodel_formdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='urlTask',
        ),
    ]
