# Generated by Django 6.0.3 on 2026-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0009_remove_taskmodel_urltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='Form 1 pending', max_length=100),
        ),
    ]
