# Generated by Django 6.0.3 on 2026-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0010_taskmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='leadId',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
