# Generated by Django 6.0.3 on 2026-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0011_taskmodel_leadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='leadId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
