# Generated by Django 6.0.1 on 2026-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0012_alter_taskmodel_leadid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
