# Generated by Django 6.0.1 on 2026-03-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_management', '0013_taskmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='formStep',
        ),
    ]
